name: Run Tests

on:
  push:
    branches:
      - main # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main # Run tests for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests/
