name: Run Tests

on:
  push:
    branches:
      - main # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main # Run tests for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Update the Python version as needed

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          poetry install --all-extras

      # Step 5: Run tests
      - name: Run tests
        run: |
          poetry run pytest
